epochs: 100
output_dir: output_dir

model:
  name: Classification
  backbone:
    name: ResNet
    depth: 50
    frozen_stages: 4
  head:
    name: ClasHead
    with_avg_pool: true
    in_channels: 2048

dataloader:
  train:
    num_workers: 6
    sampler:
      batch_size: 64
      shuffle: true
      drop_last: true
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: True
      transforms:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  val:
    num_workers: 4
    sampler:
      batch_size: 64
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val
      return_label: True
      transforms:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

lr_scheduler:
  name: MultiStepDecay
  learning_rate: 30.0
  milestones: [60, 80]


optimizer:
  name: Momentum
  weight_decay: 0.0

log_config:
    name: LogHook
    interval: 50

custom_config:
  - name: EvaluateHook
