epochs: 300
output_dir: output_dir
seed: 0

model:
  name: SwinWrapper
  architecture:
      name: SwinTransformer
      embed_dim: 128
      depths: [2, 2, 18, 2]
      num_heads: [4, 8, 16, 32]
      window_size: 7
      drop_path_rate: 0.5
  head:
    name: SwinTransformerClsHead
    with_avg_pool: True
    num_classes: 1000
    in_channels: 1024

dataloader:
  train:
    num_workers: 8
    sampler:
      batch_size: 128
      shuffle: true
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train/
      return_label: True
      transforms:
        - name: RandomResizedCrop
          size: 224
          scale: [0.08, 1.]
          interpolation: 'bicubic'
        - name: RandomHorizontalFlip
        - name: AutoAugment
          config_str: 'rand-m9-mstd0.5-inc1'
          interpolation: 'bicubic'
          img_size: 224
        - name: Transpose
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
        - name: RandomErasing
          prob: 0.25
          mode: 'pixel'
          max_count: 1
      batch_transforms:
        - name: Mixup
          mixup_alpha: 0.8
          prob: 1.
          switch_prob: 0.5
          mode: 'batch'
          cutmix_alpha: 1.0
  val:
    num_workers: 8
    sampler:
      batch_size: 128
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val
      return_label: True
      transforms:
        - name: Resize
          size: 256
          interpolation: 'bicubic'
        - name: CenterCrop
          size: 224
        - name: Transpose
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]

lr_scheduler:
  name: LinearWarmup
  learning_rate:
    name: CosineAnnealingDecay
    learning_rate: 0.001
    T_max: 300
    eta_min: 1e-5
  warmup_steps: 20
  start_lr: 1e-6
  end_lr: 0.001

optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.05
  epsilon: 1e-8
  exclude_from_weight_decay: ["absolute_pos_embed","relative_position_bias_table",".bias","norm"]
  grad_clip:
    name: global_norm
    value: 5.0


log_config:
    name: LogHook
    interval: 10

checkpoint:
  name: CheckpointHook
  by_epoch: true
  interval: 1
  max_keep_ckpts: 50

custom_config:
  - name: EvaluateHook
