epochs: 300
output_dir: output_dir
seed: 16
use_amp: True 

AMP:
   level: 'O1'
   save_dtype: 'float32'
   master_weight: True
   optimizers: None
   scale_loss: 32768.0
   auto_cast:
     enable: True
     custom_black_list: ["reduce_mean", "reduce_sum",
                         "c_softmax_with_cross_entropy", "elementwise_div"]
     level: 'O1'
sharding:
   sharding_stage: 2  # 2 or 'dp'
   offload: False 

accumulate_grad_steps: 2 

model:
  name: SwinWrapper
  architecture:
      name: SwinTransformer
      embed_dim: 354
      depths: [2, 2, 18, 2]
      num_heads: [6, 12, 24, 48]
      window_size: 7
      drop_path_rate: 0.0
      version: 2
  head:
    name: SwinTransformerClsHead
    with_avg_pool: True
    num_classes: 1000
    in_channels: 2832

dataloader:
  train:
    num_workers: 8
    sampler:
      batch_size: 8
      shuffle: true
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train/
      return_label: True
      transforms:
        - name: RandomResizedCrop
          size: 224
          scale: [0.08, 1.]
          interpolation: 'bicubic'
        - name: RandomHorizontalFlip
        - name: AutoAugment
          config_str: 'rand-m9-mstd0.5-inc1'
          interpolation: 'bicubic'
          img_size: 224
        - name: Transpose
        - name: NormalizeImage                                                                                                                                                                                                                                                 
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
        - name: RandomErasing
          prob: 0.25
          mode: 'pixel'
          max_count: 1
      batch_transforms:
        - name: Mixup
          mixup_alpha: 0.8
          prob: 1.
          switch_prob: 0.5
          mode: 'batch'
          cutmix_alpha: 1.0
  val:
    num_workers: 8
    sampler:
      batch_size: 64 
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val
      return_label: True
      transforms:
        - name: Resize
          size: 256
          interpolation: 'bicubic'
        - name: CenterCrop
          size: 224
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

lr_scheduler:
  name: LinearWarmup
  learning_rate:
    name: CosineAnnealingDecay
    learning_rate: 0.001  # 8 gpus
    T_max: 300
    eta_min: 1e-5
  warmup_steps: 20
  start_lr: 1e-6
  end_lr: 0.001

optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.05
  multi_precision: True
  epsilon: 1e-8
  exclude_from_weight_decay: ["absolute_pos_embed","relative_position_bias_table",".bias","norm"]
  grad_clip:
    name: global_norm
    value: 5.0


log_config:
    name: LogHook
    interval: 10

checkpoint:
  name: CheckpointHook
  by_epoch: true
  interval: 1
  max_keep_ckpts: 20

custom_config:
  - name: EvaluateHook
