epochs: 300
output_dir: output_dir
seed: 0
device: gpu

use_amp: True
AMP:
   level: 'O1'
   save_dtype: 'float32'
   optimizers: None
   scale_loss: 65536.0
   auto_cast:
     enable: True
     custom_black_list: ["reduce_mean", "reduce_sum",
                         "log_softmax", "elementwise_div"]
     level: 'O1'

model:
  name: DeiTWrapper
  architecture:
      name: DeiTVisionTransformer
      img_size: 224
      patch_size: 16
      embed_dim: 768
      depth: 12
      num_heads: 12
      mlp_ratio: 4
      qkv_bias: True
      epsilon: 1e-6
      num_classes: 1000
      drop_rate: 0.0
      drop_path_rate : 0.1

dataloader:
  train:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      name: DistributedRepeatedAugSampler
      batch_size: 64
      shuffle: True
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train/
      return_label: True
      transforms:
        - name: ToRGB
          return_type: numpy
        - name: RandCropImage
          size: 224
          scale: [0.05, 1.0]
          interpolation: bicubic
          backend: pil
        - name: RandomHorizontalFlip
        - name: AutoAugment
          config_str: 'rand-m9-mstd0.5-inc1'
          interpolation: 'bicubic'
          img_size: 224
        - name: Normalize
          data_format: 'HWC'
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
        - name: Transpose
        - name: RandomErasing
          prob: 0.25
          mode: 'pixel'
          max_count: 1
      batch_transforms:
        - name: Mixup
          mixup_alpha: 0.8
          prob: 1.
          switch_prob: 0.5
          mode: 'batch'
          cutmix_alpha: 1.0
          label_smoothing: 0.1
          num_classes: 1000

  val:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      batch_size: 256
      shuffle: False
      drop_last: False
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val
      return_label: True
      transforms:
        - name: ToRGB
          return_type: numpy
        - name: ResizeImage
          resize_short: 256
          interpolation: 'bicubic'
          backend: pil
        - name: CenterCrop
          size: 224
        - name: Normalize
          data_format: 'HWC'
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
        - name: Transpose

lr_config:
  name: LRSchedulerHook
  unit: 'epoch'

lr_scheduler:
  name: TimmCosine
  learning_rate: 1e-3
  eta_min: 1e-5
  warmup_epoch: 5
  warmup_start_lr: 1e-6
  T_max: 300

optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  epsilon: 1e-8
  weight_decay: 0.05
  exclude_from_weight_decay: ["cls_token","pos_embed",".bias","norm"]


log_config:
    name: LogHook
    interval: 10

checkpoint:
  name: CheckpointHook
  by_epoch: true
  interval: 1
  max_keep_ckpts: 5

custom_config:
  - name: EvaluateHook
