epochs: 300
output_dir: output_dir
seed: 0
device: gpu

model:
  name: Classification
  architecture:
      name: ConvNeXt
      depths: [3, 3, 27, 3]
      dims: [96, 192, 384, 768]
  head:
    name: ClasHead
    num_classes: 1000
    in_channels: 768

dataloader:
  train:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      batch_size: 128
      shuffle: true
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train/
      return_label: True
      transforms:
        - name: ToRGB
        - name: RandomResizedCrop
          size: 224
          scale: [0.75, 1.]
          ratio: [1., 1.]
          interpolation: 'bicubic'
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

lr_scheduler:
  name: LinearWarmup
  learning_rate:
    name: CosineAnnealingDecay
    learning_rate: 0.001  # 8 gpus
    T_max: 300
    eta_min: 1e-5
  warmup_steps: 20
  start_lr: 1e-6
  end_lr: 0.001

optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.05



log_config:
    name: LogHook
    interval: 10
