epochs: 100
output_dir: output_dir
seed: 0
device: gpu

model:
  name: Classification
  backbone:
    name: ResNet
    depth: 50
    with_pool: true
    frozen_stages: 4
    # freeze_bn: True
  head:
    name: ClasHead
    in_channels: 2048
    num_classes: 1000

dataloader:
  train:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      batch_size: 128
      shuffle: true
      drop_last: False
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: True
      transforms:
        - name: RandomResizedCrop
          size: 224
          interpolation: bicubic
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  val:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      batch_size: 64
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val
      return_label: True
      transforms:
        - name: Resize
          size: 256
          interpolation: bicubic
        - name: CenterCrop
          size: 224
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

lr_scheduler:
  name: MultiStepDecay
  learning_rate: 30.0
  milestones: [60, 75, 90]


optimizer:
  name: Momentum
  weight_decay: 0.0

log_config:
    name: LogHook
    interval: 10

custom_config:
  - name: EvaluateHook
