epochs: 300
use_byol_iters: True
total_images: 1281167
global_batch_size: 4096  # 128 * 4 * 8
output_dir: output_dir

model:
  name: MoCoBYOL
  backbone:
    name: ResNet
    depth: 50
    num_classes: 1000
    with_pool: True
  neck:
    name: NonLinearNeckV3
    in_channels: 2048
    hid_channels: 4096
    out_channels: 256
  predictor:
    name: NonLinearNeckV3
    in_channels: 256
    hid_channels: 4096
    out_channels: 256
  head:
    name: MBHead
  queue_dim: 65536
  T: 0.2
  target_decay_method: cosine # cosine
  target_decay_rate: 0.99
  align_init_network: True
  use_synch_bn: True

dataloader:
  train:
    num_workers: 8
    sampler:
      batch_size: 128
      shuffle: true
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: False
      return_two_sample: True
      transforms:
        - name: RandomResizedCrop
          size: 224
          scale: [0.08, 1.]
          interpolation: 'bicubic'
      view_trans1:
        - name: RandomHorizontalFlip
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            sigma: [0.1, 2.0]
            _PIL: False
          p: 1.0
        - name: RandomApply
          transforms:
          - name: Solarization
          p: 0.0
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      view_trans2:
        - name: RandomHorizontalFlip
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            sigma: [0.1, 2.0]
            _PIL: False
          p: 0.1
        - name: RandomApply
          transforms:
          - name: Solarization
          p: 0.5
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

lr_scheduler:
  name: CosineWarmup
  learning_rate: 4.8
  T_max: 93835
  warmup_steps: 3127
  start_lr: 0.0048
  end_lr: 4.8


optimizer:
  name: LarsMomentumOptimizer
  momentum: 0.9
  lars_weight_decay: 1.0e-6
  exclude_from_weight_decay: ['batch_norm', '.b_0']
  epsilon: 1e-9


log_config:
    name: LogHook
    interval: 10
