epochs: 100
use_simclr_iters: True
global_batch_size: 512
output_dir: output_dir
seed: 0
device: gpu

model:
  name: SimSiam
  backbone:
    name: ResNet
    depth: 50
    with_pool: True
    num_classes: 2048
    zero_init_residual: True
  predictor:
    name: NonLinearNeckV2
    in_channels: 2048
    hid_channels: 512
    out_channels: 2048
    with_bias: False
    with_avg_pool: False
  head:
    name: SimSiamContrastiveHead

dataloader:
  train:
    loader:
      num_workers: 16
      use_shared_memory: True
    sampler:
      batch_size: 64
      shuffle: true
      drop_last: true
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: False
      return_two_sample: True
      transforms:
        - name: RandomResizedCrop
          size: 224
          scale: [0.2, 1.]
      view_trans1:
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            sigma: [0.1, 2.0]
          p: 0.5
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      view_trans2:
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            sigma: [0.1, 2.0]
          p: 0.5
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

lr_scheduler:
  name: Cosinesimclr
  learning_rate: 0.1
  T_max: 100

optimizer:
  name: Momentum
  weight_decay: 0.0001

optimizer_config:
  name: SimsiamOptimizerHook

log_config:
    name: LogHook
    interval: 50

lr_config:
  name: LRSchedulerHook
  unit: epoch
