epochs: 90
use_simclr_iters: True
global_batch_size: 4096
output_dir: output_dir
seed: 0
device: gpu

model:
  name: Classification
  backbone:
    name: ResNet
    depth: 50
    frozen_stages: 4
  head:
    name: ClasHead
    with_avg_pool: true
    in_channels: 2048

dataloader:
  train:
    loader:
      num_workers: 16
      use_shared_memory: True
    sampler:
      batch_size: 512
      shuffle: true
      drop_last: true
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: True
      transforms:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  val:
    loader:
      num_workers: 16
      use_shared_memory: True
    sampler:
      batch_size: 512
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val
      return_label: True
      transforms:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

lr_scheduler:
  name: Cosinesimclr
  learning_rate: 1.6
  T_max: 90

optimizer:
  name: LarsMomentumOptimizer
  momentum: 0.9
  lars_weight_decay: 0.0

log_config:
    name: LogHook
    interval: 50

lr_config:
  name: LRSchedulerHook
  unit: epoch

custom_config:
  - name: EvaluateHook
