epochs: 100
output_dir: output_dir
seed: 0
device: gpu

# used for static mode and model export
image_shape: [3, 224, 224]
save_inference_dir: ./inference

model:
  name: DINOClassification
  backbone:
    name: VisionTransformer
    img_size: 224
    patch_size: 16
    width: 384
    depth: 12
    num_heads: 6
    mlp_ratio: 4
    epsilon: 1e-6
    frozen_weights: True
  head:
    name: ClasHead
    with_avg_pool: False
    in_channels: 1536
  n_last_blocks: 4

dataloader:
  train:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      batch_size: 32
      shuffle: True
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: True
      transforms:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  val:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      batch_size: 32
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val
      return_label: True
      transforms:
        - name: Resize
          size: 256
          interpolation: bicubic
        - name: CenterCrop
          size: 224
        - name: Transpose
        - name: NormalizeImage
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

lr_scheduler:
  name: CosineAnnealingDecay
  learning_rate: 0.003
  T_max: 100

optimizer:
  name: Momentum
  weight_decay: 0.0

log_config:
    name: LogHook
    interval: 50

custom_config:
  - name: EvaluateHook
