from .resnet import ResNet
from .clip import CLIP
from .builder import build_backbone
from .resnetcifar import ResNet
from .resnetsimclr import ResNetsimclr
from .vision_transformer import VisionTransformer
from .vit import GoogleVisionTransformer
from .swin_transformer import SwinTransformer
from .beit import Beit
from .t2t_vit import T2TViT
from .cait import Cait
from .mlp_mixer import MlpMixer
from .cvt import CvT
