epochs: 300
output_dir: output_dir

model:
  name: T2TViTWrapper
  architecture:
      name: T2TViT
      img_size: 224
      tokens_type: 'performer'
      embed_dim: 448
      depth: 19
      num_heads: 7
  head:
    name: T2TViTClsHead
    num_classes: 1000
    in_channels: 448

dataloader:
  train:
    num_workers: 0
    sampler:
      batch_size: 128
      shuffle: true
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train/
      return_label: True
      transforms:
        - name: ToRGB
        - name: RandomResizedCrop
          size: 224
          scale: [0.75, 1.]
          ratio: [1., 1.]
          interpolation: 'bicubic'
        - name: Transpose
        - name: Normalize
          mean: [127.5, 127.5, 127.5]
          std: [127.5, 127.5, 127.5]

lr_scheduler:
  name: CosineWarmup
  learning_rate: 0.003
  T_max: 93835
  warmup_steps: 10000
  start_lr: 0.00003
  end_lr: 0.003

optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.3
  grad_clip:
    name: global_norm
    value: 1.0


log_config:
    name: LogHook
    interval: 10
