# global configs
Global:
  task_type: Classification
  train_loop: ClassificationTrainingEpochLoop
  validate_loop: ClassificationEvaluationLoop
  checkpoint: null
  pretrained_model: /root/paddlejob/workspace/env_run/tangshiyu/PASSL/swav_800ep_pretrain.pdparams
  output_dir: ./output/baseline_0420_align_trackTrue
  device: gpu
  save_interval: 1
  max_num_latest_checkpoint: 0
  eval_during_train: True
  eval_interval: 1
  eval_unit: "epoch"
  accum_steps: 1
  epochs: 100
  print_batch_step: 100
  use_visualdl: False
  seed: 31

# FP16 setting ignore in align
# FP16:
#   level: O1

DistributedStrategy:
  data_parallel: True

# model architecture
Model:
  name: swav_resnet50_linearprobe
  class_num: 1000

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
  Eval:
    - CELoss:
        weight: 1.0

LRScheduler:
    name: TimmCosine
    learning_rate: 0.3
    eta_min: 0.0
    decay_unit: epoch
    last_epoch: 0
    warmup_epoch: 0

Optimizer:
  name: Momentum
  momentum: 0.9
  weight_decay: 1e-6
  tensor_fusion: True
  
# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageFolder
      root: data/ILSVRC2012/train
      transform:
        - RandomResizedCrop:
            size: 224
        - RandomHorizontalFlip:
        - ToTensor:
        - Normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.228, 0.224, 0.225]
    sampler:
      name: DistributedBatchSampler
      batch_size: 32 # accum_steps: 1, total batchsize: 256
      drop_last: False
      shuffle: True
    loader:
      num_workers: 8
      use_shared_memory: True

  Eval:
    dataset:
      name: ImageFolder
      root: data/ILSVRC2012/val
      transform:
        - Resize:
            size: 256
        - CenterCrop:
            size: 224
        - ToTensor:
        - Normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.228, 0.224, 0.225]
    sampler:
      name: DistributedBatchSampler
      batch_size: 32
      drop_last: False
      shuffle: False
    loader:
      num_workers: 8
      use_shared_memory: True

Metric:
  Train:
    - TopkAcc:
        topk: [1, 5]
  Eval:
    - TopkAcc:
        topk: [1, 5]

Export:
  export_type: paddle
  input_shape: [None, 3, 224, 224]
