# global configs
Global:
  task_type: ContrastiveLearning
  train_loop: ContrastiveLearningTrainingEpochLoop
  validate_loop: None
  checkpoint: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  save_interval: 1
  max_num_latest_checkpoint: 0
  eval_during_train: False
  eval_interval: 1
  eval_unit: "epoch"
  accum_steps: 1
  epochs: 100
  print_batch_step: 10
  use_visualdl: False
  seed: 2023

# FP16 setting
FP16:
  level: O0
  GradScaler:
    init_loss_scaling: 65536.0
    incr_every_n_steps: 2000

DistributedStrategy:
  data_parallel: True

# model architecture
Model:
  name: simsiam_resnet50_pretrain


Optimizer:
  name: Momentum
  momentum: 0.9
  weight_decay: 1e-4
  lr_decay_unit: epoch
  lr:
    name: TimmCosine
    learning_rate: 0.1
    decay_unit: epoch
    eta_min: 0.0
    warmup_epoch: 0
    warmup_start_lr: 0.0
    warmup_prefix: False
    last_epoch: 0
  param_groups:
    - name: encoder
    - name: predictor
      lr: 0.1


# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageFolder
      root: ./dataset/ILSVRC2012/train
      transform:
        - TwoViewsTransform:
            base_transform1:
              - RandomResizedCrop:
                  size: 224
                  scale: [0.2, 1.0]
                  interpolation: bicubic
              - ColorJitter:
                  p: 0.8
                  brightness: 0.4
                  contrast: 0.4
                  saturation: 0.4
                  hue: 0.1
              - RandomGrayscale:
                  p: 0.2
              - SimCLRGaussianBlur:
                  p: 0.5
                  sigma: [.1, 2.]
              - RandomHorizontalFlip:
              - ToTensor:
              - Normalize:
                  mean: [0.485, 0.456, 0.406]
                  std: [0.229, 0.224, 0.225]
            base_transform2:
              - RandomResizedCrop:
                  size: 224
                  scale: [0.2, 1.0]
                  interpolation: bicubic
              - ColorJitter:
                  p: 0.8
                  brightness: 0.4
                  contrast: 0.4
                  saturation: 0.4
                  hue: 0.1
              - RandomGrayscale:
                  p: 0.2
              - SimCLRGaussianBlur:
                  p: 0.5
                  sigma: [.1, 2.]
              - RandomHorizontalFlip:
              - ToTensor:
              - Normalize:
                  mean: [0.485, 0.456, 0.406]
                  std: [0.229, 0.224, 0.225]
    sampler:
      name: DistributedBatchSampler
      batch_size: 64 # accum_steps: 1, total batchsize: 512
      drop_last: True
      shuffle: True
    loader:
      num_workers: 8
      use_shared_memory: True
