epochs: 10
output_dir: output_dir
seed: 0
device: gpu

model:
  name: CLIPWrapper
  architecture:
    name: CLIP
    embed_dim: 512
    image_resolution: 224
    vision_layers: 12
    vision_width: 768
    vision_patch_size: 32
    context_length: 77
    vocab_size: 49408
    transformer_width: 512
    transformer_heads: 8
    transformer_layers: 12
    qkv_bias: True
    pre_norm: True
    proj: True
    patch_bias: False
  head:
    name: CLIPHead

dataloader:
  train:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      batch_size: 128
      shuffle: true
      drop_last: True
    dataset:
      name: TextImageDataset
      dataroot: data/FOOD101/captions/
      transforms:
        - name: ToRGB
        - name: RandomResizedCrop
          size: 224
          scale: [0.75, 1.]
          ratio: [1., 1.]
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      shuffle: False

lr_scheduler:
  name: LinearWarmup
  learning_rate:
    name: CosineAnnealingDecay
    learning_rate: 0.0001  # 8 gpus
    T_max: 10
    eta_min: 1e-6
  warmup_steps: 5
  start_lr: 0
  end_lr: 0.0001

optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.98
  epsilon: 1e-8
  weight_decay: 0.0005

log_config:
    name: LogHook
    interval: 10
