epochs: 100
output_dir: output_dir
seed: 0
device: gpu

model:
  name: ByolClassification
  backbone:
    name: ResNet
    depth: 50
    with_pool: true
    frozen_stages: 4
  head:
    name: ClasHead
    with_avg_pool: false
    in_channels: 2048
    num_classes: 1000

dataloader:
  train:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      batch_size: 128
      shuffle: true
      drop_last: False
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: True
      transforms:
        - name: ByolRandomCrop
        - name: RandomHorizontalFlip
        - name: Resize
          size: [224,224]
          interpolation: bicubic
        - name: ByolNormalize
        - name: Clip
  val:
    loader:
      num_workers: 8
      use_shared_memory: True
    sampler:
      batch_size: 128
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val #subtrain
      return_label: True
      transforms:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ByolNormalize
        - name: Clip

lr_scheduler:
  name: ByolLRScheduler
  total_image: 1281167
  total_batch: 1024
  total_steps: 100
  warmup_steps: 0
  start_lr: 0.0001
  end_lr: 1.6

optimizer:
  name: Momentum
  use_nesterov: true

log_config:
    name: LogHook
    interval: 10

custom_config:
  - name: EvaluateHook
